import { synonymKeys, normalize } from './quizBank.js';

const lyricsMap = {
  math: {
    'Shapes': `🎵 A circle is round and has no sides at all, it rolls on the ground like a bouncing ball!\nA square has four equal sides you see, a rectangle has two long and two short for me!\nA triangle has three sides and three corners neat, learning basic shapes is really sweet!\n\n🎵 Chorus: Shapes are everywhere we go, in the world below and above, learning every shape with love!\n\n🎵 An oval stretches like an egg so wide, a diamond has four corners like a kite with pride!\nA star has five shining points so bright, a hexagon has six sides left and right!\nA cube has six square faces all around, a sphere is round like a ball on the ground!`,
    'Numbers 1 to 9': `🎵 One two three count with me, learning numbers is the key!\nFour five six do the tricks, seven eight nine combine and mix!\n\n🎵 Chorus: Numbers help us count each day, in the classroom and at play!\n\n🎵 One sun shines so bright and warm, two eyes see the world in form!\nThree little birds sing a song, four legs on a cat move along!\nFive fingers on my little hand, six petals on flowers in the land!\nSeven days are in a week, eight legs on an octopus sleek!\nNine planets used to orbit the Sun, counting numbers is so much fun!`,
    'Numbers 1-100': `🎵 Count from one to one hundred strong, learning numbers all day long!\nTen twenty thirty count by tens, counting numbers makes good sense!\n\n🎵 Chorus: Numbers from one to one hundred and more, knowing them opens every door!\n\n🎵 After ninety-nine comes one hundred you see, round numbers like fifty are easy as can be!\nTwo-digit numbers have tens and ones place, like twenty-five has two tens and five ones to face!\nCount by fives from five to one hundred tall, five ten fifteen twenty learning has no wall!\nEven numbers end in zero two four six eight, odd numbers end in one three five seven nine great!`,
    'Addition': `🎵 One plus one equals two, that is easy to do! Two plus two equals four, adding more and more!\nThree plus three equals six, doing addition tricks! Adding numbers every day, learning math is here to stay!\n\n🎵 Chorus: Addition means to put together, like the sun and rainy weather! Add the numbers, count them all, big and small!\n\n🎵 Add three apples on a tree, add two more and we can see five apples now for me!\nFour balloons up in the sky, add one more flying by, now we have as many as five up high!\nSix birds sitting on the wire, add three more and we spy nine birds up in the sky!\nWhen we add zero to any number in sight, the number stays the same and that is right!`,
    'Subtraction': `🎵 Five minus two equals three we know, taking away is easy to show!\nTen minus four is six that is the way, subtraction helps us every day!\n\n🎵 Chorus: Subtract means take away some, when numbers become less we find the sum!\n\n🎵 Eight cookies sitting on your plate, eat three of them before it's late,\nNow you have five cookies left to eat, subtraction makes math complete!\nSeven birds are sitting on a tree, four fly away for all to see,\nNow three are left upon the branch, subtraction helps us count them back!\nWhen you subtract a number from itself you see, the answer is always zero as can be!`,
    'Addition & Subtraction': `🎵 Addition and subtraction are a pair, one puts together and one takes care!\nAddition makes the numbers grow so tall, subtraction makes them become small!\n\n🎵 Chorus: Add and subtract every day, in work in fun in every way!\n\n🎵 Check subtraction with addition you see, if eight minus three is five then five plus three is eight for me!\nTwenty-five plus fifteen equals forty in all, forty minus fifteen is twenty standing tall!\nWord problems use both to help us find the way, add or subtract depending what they say!\nIf you have fifty rupees and spend thirty at the store, twenty rupees remain and you need no more!`,
    'Multiplication': `🎵 Multiplication is repeated addition let me explain, two times four is eight again and again!\nWhen we multiply we are adding groups with speed, two plus two plus two plus two is eight indeed!\n\n🎵 Chorus: Times tables learn them all by heart, two times two is four that is very smart!\nMultiplication makes math easy day and night, learning times tables feels right!\n\n🎵 Two times one is two, two times two is four, two times three is six learn some more!\nTwo times four is eight, two times five is ten, two times six is twelve once again!\nThree times one is three, three times two is six, three times three is nine learning tricks!\nFive times five is twenty-five as you can see, ten times ten is one hundred happily!`,
    'Division': `🎵 Ten divided by two equals five, division helps numbers come alive!\nTwelve divided by three is four, sharing equally is what division is for!\n\n🎵 Chorus: Division means sharing into equal parts, it takes a good mathematical heart!\n\n🎵 Fifteen divided by three is five we know, twenty divided by four is five just so!\nShare eight toys with two friends at play, each friend gets four toys hip hooray!\nDivision is the opposite of multiply, if six times three is eighteen then eighteen by three is six my oh my!\nWhen you divide a number by itself you see, the answer is always one naturally!`,
    'Fractions': `🎵 Half of eight is four easy to see, a quarter of twenty is five like a bee!\nA third of nine is three that is the way, fractions help us share every day!\n\n🎵 Chorus: Fractions are equal parts of a whole, learning them is a wonderful goal!\n\n🎵 A pizza cut into four slices you see, one slice is one quarter or one fourth for me!\nA chocolate bar with eight pieces so sweet, one piece is one-eighth a tasty treat!\nHalf means one of two equal parts, one third means one of three with all hearts!\nFractions on a number line from zero to one, numerator over denominator under the Sun!`,
    'Time': `🎵 The clock shows us time throughout the day, the hour hand points the way!\nThe minute hand runs around the dial, time tells us when to work and smile!\n\n🎵 Chorus: A day has twenty-four hours so grand, sixty minutes in an hour as we understand!\n\n🎵 The short hand is the hour hand slow, the long hand is the minute that we know!\nWhen the minute hand is at twelve it is o'clock so clear, when it reaches six it is half past my dear!\nQuarter past means fifteen minutes have gone by, quarter to means fifteen minutes left till the hour is nigh!\nAM is morning from midnight to noon, PM is afternoon and evening soon!`,
    'Money': `🎵 A penny is one cent that is clear, a nickel is five cents have no fear!\nA dime is ten cents a quarter twenty-five, count your money and you will thrive!\n\n🎵 Chorus: Money money coins and bills we use, learning to count it you cannot lose!\n\n🎵 A dollar bill equals one hundred cents, knowing money makes good sense!\nFour quarters make a dollar as we know, ten dimes make a dollar all in a row!\nTwenty nickels make a dollar too, one hundred pennies make a dollar for you!\nAdding coins and bills helps us shop and save, learning about money is something to crave!`,
    'Tables 2-5': `🎵 Two times table learn with me, two four six eight ten as can be!\nThree times table follow along, three six nine twelve sing the song!\n\n🎵 Chorus: Tables from two to five are fun to know, they help our math skills grow!\n\n🎵 Two ones are two two twos are four, two threes are six and learn some more!\nTwo fours are eight two fives are ten, two sixes are twelve once again!\nThree ones are three three twos are six, three threes are nine learning tricks!\nFour ones are four five ones are five, knowing tables helps us thrive!`,
    'Time & Money': `🎵 Time and money go hand in hand, managing both is something grand!\nHours and minutes tell the day, coins and bills help us pay!\n\n🎵 Chorus: Time tells us when, money tells the cost, learning both is never lost!\n\n🎵 If you save two rupees every day for a week of seven, fourteen rupees you will keep that is money heaven!\nIf you start your homework at four and finish at half past, thirty minutes have gone by very fast!\nA dollar is one hundred cents or four quarters neat, an hour is sixty minutes a very useful feat!\nOne rupee coin ten rupee note money we can count, time and money management really does amount!`,
    'Fun with Numbers': `🎵 Numbers can be fun to explore, patterns and puzzles and so much more!\nSkip counting by twos threes fives and tens, number patterns help us make amends!\n\n🎵 Chorus: Fun with numbers every day, find the pattern all the way!\n\n🎵 What comes next in the pattern two four six, the answer is eight get it fixed!\nThree six nine twelve what follows you ask, fifteen is the answer to this task!\nOdd numbers end in one three five seven nine, even numbers in zero two four six eight do shine!\nA palindrome like 121 reads the same both ways, number fun is amazing always!`,
    'Large Numbers': `🎵 Numbers get larger as we go, thousands ten thousands even more you know!\nOne thousand has three zeroes at its end, ten thousand has four digits to transcend!\n\n🎵 Chorus: Large numbers big and grand, help us understand the land!\n\n🎵 One thousand is ten hundreds in a row, ten thousand is ten thousands watch them grow!\nLakh has five digits one zero zero zero zero, crore has seven digits a very large hero!\nIn the number 9,876 each digit has a place, nine thousands eight hundreds seven tens six ones face!\nReading large numbers from left to right, helps us get the value right!`,
    'Place Value': `🎵 Every digit has a place in a number you see, ones tens hundreds and thousands for me!\nIn the number 345 the three is hundreds place,\nthe four is tens and the five is ones face!\n\n🎵 Chorus: Place value tells us what each digit means, from the ones to the tens to the hundreds scenes!\n\n🎵 In 4,832 the four is thousands so grand, the eight is hundreds in the place land!\nExpanded form breaks a number apart, like 300 plus 20 plus 5 equals 325 smart!\nWhen we add we line up digits by their place, ones under ones tens under tens face to face!\nUnderstanding place value helps us read and write, every big number day and night!`,
    'Roman Numerals': `🎵 Roman numerals are ancient you see, I equals one V equals five and X is ten for me!\nL is fifty C is one hundred and D is five hundred too, M is one thousand learning them is fun to do!\n\n🎵 Chorus: Roman numerals old and grand, used in clocks and books throughout the land!\n\n🎵 When a smaller letter comes before a larger one subtract, like IV is four from five minus one exact!\nWhen a smaller letter comes after you add it in, like VI is six from five plus one begin!\nVII is seven VIII is eight IX is nine neat, XI is eleven XII is twelve complete!\nYears and chapters and clock faces too, show Roman numerals for me and you!`,
    'Factors & Multiples': `🎵 Factors are numbers that divide evenly you see, like factors of twelve are one two three four six and twelve for me!\nMultiples are what you get when you multiply, like multiples of three are three six nine twelve up high!\n\n🎵 Chorus: Factors and multiples a math pair, finding them beyond compare!\n\n🎵 A prime number has only two factors neat, one and itself a prime is complete!\nTwo three five seven eleven thirteen are prime, they have been known for a very long time!\nThe greatest common factor of twelve and eighteen is six, the largest that divides both without any tricks!\nThe least common multiple of three and four is twelve, the smallest shared multiple that helps us delve!`,
    'Geometry': `🎵 Geometry is the study of shapes and space, points lines and angles every place!\nA point is an exact location small, a line goes on forever through it all!\n\n🎵 Chorus: Geometry helps us understand, the shapes and space across the land!\n\n🎵 A line segment has two endpoints you see, a ray has one endpoint going endlessly!\nAn angle forms where two lines meet, acute is less than ninety degrees so neat!\nA right angle is exactly ninety degrees square, an obtuse angle is more than ninety there!\nParallel lines never meet side by side, perpendicular lines at right angles do ride!`,
    'Perimeter & Area': `🎵 Perimeter is the distance around a shape you see, add all the sides to find it easily!\nArea is the space inside measured in square units, covering the surface with squares and fruits!\n\n🎵 Chorus: Perimeter around and area inside, measuring shapes with nothing to hide!\n\n🎵 The perimeter of a square is four times the side, of a rectangle length plus width doubled with pride!\nArea of a rectangle is length times width so grand, area of a square is side times side of the land!\nSquare centimeters and square meters measure area space, the bigger the shape the greater the space you face!\nFinding the area of irregular shapes by counting squares, learning measurement beyond compares!`,
    'Measurement': `🎵 Measurement helps us know how big or small, how long how heavy how tall!\nLength is measured in meters centimeters and more, weight in grams and kilograms to explore!\n\n🎵 Chorus: Measure measure all around, in the school and on the ground!\n\n🎵 One meter has one hundred centimeters you see, one kilometer has one thousand meters for me!\nA ruler measures length in centimeters and inches too, a tape measure around things like a shoe!\nWeight is measured on a scale with grams and kilos, temperature on a thermometer wherever we go!\nCapacity in liters and milliliters for liquid we hold, measuring is important like a story told!`,
    'Symmetry': `🎵 Symmetry means both sides match like a mirror reflection, dividing a shape in equal parts with perfection!\nA line of symmetry cuts a shape in two equal halves you see, like a butterfly or a leaf on a tree!\n\n🎵 Chorus: Symmetry symmetric balanced and neat, where both sides perfectly meet!\n\n🎵 A square has four lines of symmetry through it, a rectangle has two lines now you get it!\nA circle has infinite lines of symmetry so round, a triangle's symmetry depends if it is equilateral found!\nReflection symmetry is like a mirror image clear, rotational symmetry spins around a center dear!\nButterflies and snowflakes have symmetry by nature's art, symmetrical designs are beautiful and smart!`,
    'Decimals': `🎵 Decimals show parts of a whole like fractions do, the decimal point separates the whole from the tenths crew!\nOne tenth is zero point one as clear as day, one hundredth is zero point zero one in every way!\n\n🎵 Chorus: Decimals are fractions in another form, learning them keeps our knowledge warm!\n\n🎵 Zero point five is the same as one half you see, zero point twenty five is one quarter for me!\nTenths are the first digit after the decimal point, hundredths are the second digit in this joint!\nWhen adding decimals line up the points with care, when comparing look at tenths place compare!\nFive tenths is greater than five hundredths this is true, decimals are useful in money and science too!`,
    'Percentage': `🎵 Percentage means out of one hundred every time, fifty percent is fifty out of one hundred in rhyme!\nOne hundred percent is the whole or all you see, fifty percent is exactly a half for me!\n\n🎵 Chorus: Percentage percent out of one hundred, learning it leaves you well-remembered!\n\n🎵 Twenty-five percent is the same as one quarter grand, ten percent of fifty is five you understand!\nTo find ten percent of any number just divide by ten, twenty percent of forty is eight once again!\nPercentages are used in discounts at the store, if something is twenty percent off you pay eighty percent more!\nIn a test if you get ninety out of one hundred right, your score is ninety percent shining bright!`,
    'Volume': `🎵 Volume is the space inside a three-dimensional shape, measured in cubic units with no escape!\nA cube's volume is side times side times side in three, length times width times height for a box you see!\n\n🎵 Chorus: Volume cubic space inside, where things can fit and hide!\n\n🎵 A cube with side two has volume of eight so grand, length times width times height as we understand!\nLiters measure liquid volume for water and milk, milliliters measure small amounts smooth as silk!\nOne liter equals one thousand milliliters you know, volume helps us measure where liquids flow!\nA cubic centimeter is a cube one centimeter each side, volume is fun to learn with nothing to hide!`,
    'Speed': `🎵 Speed tells how fast something moves through space, distance divided by time at every pace!\nIf you run ten meters in five seconds your speed is two meters each second indeed!\n\n🎵 Chorus: Speed speed how fast we go, distance over time to show!\n\n🎵 Speed is measured in kilometers per hour on the road, or meters per second in a science mode!\nA car moving at sixty kilometers per hour is fast, a bicycle at fifteen per hour will last!\nSpeed equals distance divided by time so clean, if you travel one hundred kilometers in two hours your speed is fifty I mean!\nAverage speed is total distance over total time you take, faster speed means more distance you make!`,
    'Data Handling': `🎵 Data handling is collecting information to see, organizing it in tables and charts for you and me!\nTally marks count in groups of five so neat, four lines and a cross to make five complete!\n\n🎵 Chorus: Data information all around, organizing it is profound!\n\n🎵 A bar graph shows data with bars of different height, comparing values with colors so bright!\nThe tallest bar shows the largest number in the chart, each bar's height corresponds to a part!\nA pictograph uses pictures to show data so clear, each picture represents a certain number dear!\nTally charts count occurrences one by one, the total is the count when all is done!`,
    'Graphs': `🎵 Graphs help us see data visually you know, with bars and lines and pictures on show!\nThe x-axis runs horizontal left to right, the y-axis runs vertical with all its might!\n\n🎵 Chorus: Graphs tell stories with art and scale, data stories never fail!\n\n🎵 A bar graph compares groups with bars so tall, a line graph shows how things change through it all!\nA pie chart shows parts of a whole circle so grand, each slice a percentage of the land!\nThe title tells what the graph is about, the labels on axes help figure out!\nReading graphs helps us understand data better, from weather charts to a fund-raising letter!`,
    'Factors': `🎵 Factors are numbers that divide exactly in two, like one two four and eight are factors of eight for you!\nEvery number has one and itself as a factor pair, finding all factors is a math task beyond compare!\n\n🎵 Chorus: Factor factor pair them right, divide evenly day and night!\n\n🎵 Factors of twelve are one two three four six and twelve, factors of fifteen are one three five fifteen where you delve!\nTo find factors of a number start with one and go, check each number that divides evenly and you will know!\nThe greatest common factor of two numbers find, the biggest one that divides both like the largest of its kind!`
  },
  science: {
    'My Body': `🎵 My body from head to toe is amazing you see, every part works together for you and me!\nThe head has a brain to think and learn each day, senses help us see and hear and touch in every way!\n\n🎵 Chorus: My body wonderful and grand, the most amazing in the land!\n\n🎵 Two eyes to see the world so bright, two ears to hear both day and night!\nA nose to smell the flowers sweet, a mouth to taste the food we eat!\nTwo hands to hold and clap and play, two legs to walk and run each day!\n\nThe heart pumps blood throughout our body so strong, the lungs help us breathe air all day long!\nThe stomach digests the food we take in, the brain controls everything from within!\nBones give our body structure and shape, muscles help us move and escape!\nSkin protects us from the outside world so grand, my body is the best in the land!`,
    'Heart': `🎵 The heart is a muscular pump inside your chest, it beats and beats and never takes a rest!\nIt pumps blood through vessels all around, to every part where oxygen is found!\n\n🎵 Chorus: Your heart works day and night, keeping your body right!\n\n🎵 The heart has four chambers two on each side, the atria receive blood the ventricles push it worldwide!\nThe right side pumps blood to the lungs for air, the left side pumps it to the body everywhere!\nArteries carry blood away from the heart so strong, veins carry blood back all day long!\nCapillaries connect them tiny and thin, this is how circulation begins!\n\nYour heart beats about one hundred thousand times a day, pumping blood in a wonderful way!\nEating healthy and exercise keep your heart strong, a healthy heartbeat sings a happy song!`,
    'Plants': `🎵 Plants are living things that grow so green, the most important living thing ever seen!\nThey take in sunlight water and air, to make their own food with love and care!\n\n🎵 Chorus: Plants give us food and oxygen too, there is nothing they cannot do!\n\n🎵 Roots grow underground and take in water and nutrients from the soil, the stem carries them up through all the toil!\nLeaves make food using sunlight in a process called photosynthesis so grand, chlorophyll in leaves makes them green across the land!\nFlowers make fruits that carry seeds inside, new plants from those seeds grow with nature as their guide!\nPlants give us fruits and vegetables to eat, cotton for clothes and wood for houses so neat!`,
    'Plants Around Us': `🎵 Plants are all around the world you see, from tiny moss to a giant banyan tree!\nRoots hold the plant firm and take in water deep, from the soil the plant takes what it needs to keep!\n\n🎵 Chorus: Plants around us every day, giving us so much in every way!\n\n🎵 The stem supports the plant up high, carrying water and food to the sky!\nLeaves make food using sunlight so bright, they work all day and into the night!\nFlowers bloom in colors bright and fair, fruits grow from flowers with seeds to share!\nCotton from plants becomes the clothes we wear, trees give us shade and clean fresh air!`,
    'Animals': `🎵 Animals live on land in water and in the air, big and small everywhere!\nThey need food water and shelter to survive, they are all wonderful and alive!\n\n🎵 Chorus: Animals all different every kind, with amazing bodies and minds!\n\n🎵 Mammals have fur or hair and feed their young with milk you know, birds have feathers and wings to help them fly and show!\nReptiles have scales and lay their eggs on land, fish live in water with gills to breathe and fins so grand!\nAmphibians live in water and on land too, insects have six legs and a body in parts a few!\nHerbivores eat only plants and grass, carnivores eat meat as they pass, omnivores eat both plants and meat to complete the class!`,
    'Animals & Birds': `🎵 Animals and birds are all around, on the ground and in the air they are found!\nMammals have fur or hair warm and thick, birds have feathers light and quick!\n\n🎵 Chorus: Animals and birds in nature's plan, every one since life began!\n\n🎵 Dogs and cats are mammals that we see every day, cows and goats on the farm in every way!\nEagles and sparrows are birds that fly up high, penguins cannot fly but they swim by!\nBirds have beaks to eat and wings to soar, they build nests in trees and on the floor!\nBirds lay eggs with a hard shell outside, from which their babies come with nothing to hide!`,
    'Food & Health': `🎵 Food gives us energy to work and play all day, we need good food in every single way!\nA balanced diet has fruits vegetables grains and more, proteins vitamins and minerals to explore!\n\n🎵 Chorus: Eat a rainbow of foods to stay healthy and bright, nutritious food makes everything right!\n\n🎵 Carbohydrates from rice wheat and bread give us energy to go ahead!\nProteins from eggs meat and beans help us grow strong as can be!\nVitamins from fruits and vegetables keep us from getting sick, calcium from milk builds bones strong and quick!\nDrink plenty of water through the day, washing toxins and germs away!`,
    'Food & Nutrition': `🎵 Nutrients are substances in food that help us grow, each type of nutrient does a job we should know!\nCarbohydrates give us energy to play and run, proteins help build muscles second to none!\n\n🎵 Chorus: Food and nutrition every meal, knowing what to eat is a big deal!\n\n🎵 Fats give us energy stored away, vitamins keep diseases at bay!\nMinerals like iron and calcium keep our bodies strong, fiber helps digestion all day long!\nA balanced diet has all nutrients in the right amount, eating well is what really does count!\nJunk food has empty calories with no nutrition to find, healthy food is good for body and mind!`,
    'Weather': `🎵 Weather is the condition of the air outside, sunny cloudy rainy with nothing to hide!\nThe sun gives us heat and light so bright, the wind can blow with all its might!\n\n🎵 Chorus: Weather changes every day, in every season in every way!\n\n🎵 Sunny days are warm and bright, cloudy days block the sunlight!\nRainy days bring water from above, snowy days with cold and love!\nWindy days make the trees sway, stormy days with thunder and lightning at play!\nA thermometer measures temperature hot or cold, weather is a story nature has told!`,
    'Living Things': `🎵 Living things grow and change each day, non-living things always stay the same!\nLiving things need food water and air to survive, they are born they grow and reproduce to thrive!\n\n🎵 Chorus: Living things are full of life, through happiness and strife!\n\n🎵 Plants are living things that grow from seeds, animals have different wants and needs!\nLiving things respond to changes all around, they move to new places on the ground!\nLiving things breathe in oxygen and breathe out carbon dioxide, they need the right environment to abide!\nNon-living things like rocks and chairs do not grow, they do not need food or water you know!`,
    'Living & Non-Living': `🎵 Living things can move and grow and change, non-living things stay the same in their range!\nA dog is living it breathes and eats, a table is non-living it has no heartbeat!\n\n🎵 Chorus: Living and non-living all around, different things on the ground!\n\n🎵 Living things need food and water and air, non-living things do not need any care!\nLiving things can make more of their own kind, non-living things you will never find!\nA plant is living it grows towards the light, a stone is non-living it stays in sight!\nAnimals and people are living things for sure, books and pencils are non-living and pure!`,
    'Our Body': `🎵 Our body has many systems working as a team, helping us to live and move and dream!\nThe skeletal system has two hundred six bones so grand, giving shape and structure across the land!\n\n🎵 Chorus: Body systems work together every day in the most amazing way!\n\n🎵 The skull protects our brain up in our head, the rib cage guards our heart and lungs instead!\nThe muscular system helps us move our arms and more, strong muscles flexing from the floor!\nThe digestive system turns our food into energy grand, starting with our mouth and teeth then stomach planned!\nThe respiratory system brings oxygen in and carbon dioxide out, the circulatory system pumps blood all about!`,
    'Human Body': `🎎 The human body is a wonderful machine, with organs and systems working unseen!\nThe skin is the largest organ covering us all, protecting us from harm standing tall!\n\n🎵 Chorus: Human body amazing and grand, the best machine in the land!\n\n🎵 The brain controls everything we think and do, the heart pumps blood the whole day through!\nThe lungs bring oxygen in for our cells, the stomach digests food where it dwells!\nThe liver cleans our blood like a filter so fine, the kidneys remove waste in a straight line!\nThe skeleton gives our body its shape and form, the muscles help us move and perform!`,
    'Air & Water': `🎵 Air is all around us everywhere you go, we breathe it in and out you know!\nWater flows in rivers lakes and sea, water is essential for you and for me!\n\n🎵 Chorus: Air and water precious you see, we need them both to be happy and free!\n\n🎵 We breathe air through our nose and our mouth, the wind blows air from south to north!\nWater falls as rain from clouds up high, we drink water when we are thirsty and dry!\nWe use water to wash and to clean, the most precious resource ever seen!\nWithout air we cannot live for long, without water nothing can grow strong!`,
    'Water': `🎵 Water covers most of our planet Earth you see, it is essential for both you and for me!\nWater changes form from solid to liquid to gas, it moves through the water cycle as we pass!\n\n🎵 Chorus: Water water all around, in the sky and on the ground!\n\n🎵 Evaporation is when water turns to vapor in the air, from oceans lakes and rivers everywhere!\nCondensation is when vapor turns to clouds in the sky, precipitation is when water falls as rain from high!\nCollection is when water gathers in rivers lakes and sea, the water cycle continues endlessly!\nWater can be solid as ice and snow, liquid as rain and gas as vapor you know!\nClean water is important for drinking and for health, saving water is a duty not for wealth!`,
    'Our Environment': `🎵 Our environment is everything around us you see, the air the water the land and every tree!\nAll living things depend on the environment to survive, keeping it clean helps us all to thrive!\n\n🎵 Chorus: Our environment precious and dear, let us protect it year after year!\n\n🎵 Pollution harms our air water and land, from factories cars and waste on the land!\nRecycling paper plastic and glass, helps our environment last!\nPlanting trees gives us oxygen clean, keeping our environment green!\nSaving water and electricity too, helps the environment for me and you!`,
    'Matter': `🎵 Matter is anything that takes up space and has weight, everything in the universe is matter great!\nMatter comes in three states solid liquid and gas, changing from one to another as we pass!\n\n🎵 Chorus: Matter matter all around, solid liquid gas on the ground!\n\n🎵 Solids have a fixed shape that stays the same, like a rock or a table you can name!\nLiquids flow and take the shape of their container so, like water or milk wherever they go!\nGases have no fixed shape and spread out wide, like air or oxygen that cannot hide!\nWhen a solid melts it becomes a liquid you see, when a liquid boils it becomes a gas for me!\nWhen a gas condenses it becomes a liquid again, changing states is a cycle without end!`,
    'States of Matter': `🎵 Matter comes in three states you know, solid liquid gas watch them go!\nSolid has a shape that always stays, liquid flows in different ways!\n\n🎵 Chorus: Solids liquids gases all around, states of matter easily found!\n\n🎵 Ice is solid water frozen cold, when it melts to liquid it can be poured!\nWhen water boils it turns to steam above, gas is water vapor as light as a dove!\nFreezing turns liquid water to solid ice, melting turns solid to liquid nice!\nEvaporation turns liquid to gas in the air, condensation turns gas to liquid everywhere!\nEvery material on Earth you see is one of these states of matter be!`,
    'Force & Work': `🎵 A force is a push or a pull you see, it makes things move or change shape for me!\nWork is done when a force moves something a distance through, like pushing a box or pulling a shoe!\n\n🎵 Chorus: Force and work go hand in hand, helping us move across the land!\n\n🎵 Gravity is the force that pulls things down to the ground, friction is the force that slows things down all around!\nMagnetic force pulls or pushes metal things so neat, muscular force from our bodies is a powerful feat!\nWork equals force times distance as scientists know, the harder you push the farther things go!\nA machine helps us do work with less force to use, like a lever a pulley or a simple screw!`,
    'Simple Machines': `🎵 Simple machines make work easier for you and me, they use less force and help us work easily!\nA lever is a bar that pivots on a point so neat, like a seesaw or a crowbar a useful feat!\n\n🎵 Chorus: Simple machines six in all, helping us when problems call!\n\n🎵 A pulley lifts heavy things with a wheel and a rope, like raising a flag on a pole is full of hope!\nAn inclined plane is a ramp that helps things slide up or down, like a wheelchair ramp into the town!\nA wedge is like a knife that splits things in two, an axe or a needle are wedges for you!\nA screw is an inclined plane wrapped around a rod, like a light bulb or a jar lid made by God!\nA wheel and axle helps things roll along so free, like a bicycle wheel or a doorknob for me!`,
    'Human Senses': `🎵 Humans have five senses to explore the world you see, sight taste touch smell and hearing for me!\nEyes help us see colors shapes and light, ears help us hear sounds day and night!\n\n🎵 Chorus: Five senses five ways to know, about the world wherever we go!\n\n🎵 The tongue tastes sweet salty sour and bitter too, the nose smells flowers and food that we chew!\nThe skin feels hot cold soft and rough, our senses are more than enough!\nEach sense has a special organ that helps it work, the eye the ear the skin the tongue the nose never shirk!\nOur senses send messages to the brain so fast, telling us about the world that will last!`,
    'Digestion': `🎵 Digestion begins in the mouth where teeth chew food so small, saliva helps break it down once and for all!\nThen it travels down the esophagus to the stomach you see, where digestive juices break it down for me!\n\n🎵 Chorus: Digestion digestion turning food to energy, the way our bodies get what they need to be!\n\n🎵 The stomach churns the food mixing it around, breaking it into a liquid that can be found!\nThe small intestine absorbs nutrients into the blood so grand, this is where the food moves across the land!\nThe liver helps process nutrients and cleans the blood so clean, the pancreas makes juices that help digest what we have seen!\nThe large intestine absorbs water and makes waste, the digestive system works with great haste!`,
    'Adaptations': `🎵 Adaptations are special features that help living things survive, helping them stay safe and thrive!\nStructural adaptations are body parts like a giraffe's long neck, behavioral adaptations are actions for survival what the heck!\n\n🎵 Chorus: Adaptations help creatures survive, keeping them healthy and alive!\n\n🎵 A polar bear has thick fur to stay warm in the cold, a camel's hump stores fat as a story told!\nA cactus has spines instead of leaves to save water so rare, a fish has gills to breathe in water everywhere!\nBirds have wings to fly away from danger and fear, chameleons change color to disappear!\nPlants in the desert have long roots to find water deep, adaptations help all living things their promises keep!`,
    'Solar System': `🎵 Our solar system has eight planets orbiting the Sun so bright, each one different day and night!\nMercury Venus Earth and Mars are the inner planets near the Sun, Jupiter Saturn Uranus Neptune the outer planets everyone!\n\n🎵 Chorus: The Sun is a star at the center of space, each planet has its very own place!\n\n🎵 Mercury is closest to the Sun so hot by day, Venus is the hottest planet in every way!\nEarth is our home with water air and life so grand, Mars is the red planet with dust and sand!\nJupiter is the biggest planet with a giant red spot, Saturn has rings of ice that are very hot!\nUranus spins on its side so unique and rare, Neptune is the farthest planet with the coldest air!`,
    'Rocks & Minerals': `🎵 Rocks are made of minerals from deep in the Earth you see, each rock has a story about geology!\nIgneous rocks form from melted lava that cools so slow or fast, like granite and basalt that will last!\n\n🎵 Chorus: Rocks and minerals all around, found above and underground!\n\n🎵 Sedimentary rocks form from sand mud and shells pressed tight, like sandstone and limestone in layers so bright!\nMetamorphic rocks form from heat and pressure deep inside, like marble and slate with nothing to hide!\nMinerals are natural solids with a crystal shape so grand, like diamond the hardest mineral in the land!\nFossils are remains of ancient life in rocks we find, giving clues to creatures from a different time!`,
    'Photosynthesis': `🎵 Photosynthesis is how plants make their own food you see, using sunlight water and carbon dioxide happily!\nChlorophyll in leaves gives them their green color bright, absorbing sunlight to make food from morning to night!\n\n🎵 Chorus: Photosynthesis makes food and oxygen too, there is nothing plants cannot do!\n\n🎵 The plant takes water from the soil through roots so deep, carbon dioxide from the air through leaves that peep!\nSunlight is absorbed by chlorophyll in leaves so green, the most amazing process ever seen!\nOxygen is released for us to breathe so free, glucose is the food made for the plant and tree!\nPhotosynthesis happens in the chloroplasts of leaf cells, the most important process science tells!`,
    'Electricity': `🎵 Electricity is a form of energy that flows, through wires and circuits as everyone knows!\nIt powers lights and fans and computers too, electricity helps in all we do!\n\n🎵 Chorus: Electricity flowing free, powering our world for you and me!\n\n🎵 A battery stores electricity like a tiny power station, it has a positive and negative connection!\nA circuit is a closed path where electricity flows, through wires a switch and a bulb that glows!\nConductors like metal let electricity pass through, insulators like plastic stop it from reaching you!\nA switch opens or closes a circuit with a click, turning things on and off real quick!\nAlways be safe with electricity around, never stick fingers in sockets on the ground!`,
    'Natural Resources': `🎵 Natural resources come from the Earth you see, like water air and wood for you and for me!\nSome resources are renewable can be used again and again, like sunlight and wind and falling rain!\n\n🎵 Chorus: Natural resources from the land, use them wisely and lend a hand!\n\n🎵 Sunlight gives us energy from the Sun so bright, wind energy spins turbines day and night!\nWater energy comes from rivers and from the sea, these renewable resources for you and me!\nCoal petroleum and natural gas are fossil fuels so old, they take millions of years to make as we are told!\nFossil fuels are non-renewable and will run out one day, so save energy in every possible way!`,
    'Plant Reproduction': `🎵 Plants reproduce to make new plants you see, through seeds and spores and stems for me!\nFlowers are the reproductive part of a plant so grand, they make seeds that grow into new plants across the land!\n\n🎵 Chorus: Plant reproduction makes new life, through seasons of joy and strife!\n\n🎵 Pollination is when pollen moves from one flower to another, carried by bees birds wind and other!\nBees are important pollinators collecting nectar so sweet, they carry pollen on their bodies and feet!\nSeeds grow into new plants through germination we know, with water warmth and soil the seeds begin to grow!\nSome plants reproduce through stems like potatoes in the ground, or through leaves and roots where new plants are found!`,
    'Plant Life': `🎵 A plant's life cycle begins with a seed so small, with water soil and sunlight it starts to grow tall!\nGermination is when the seed sprouts and a root appears, a tiny shoot grows upward overcoming all fears!\n\n🎵 Chorus: Plant life cycle seed to flower, nature's power hour by hour!\n\n🎵 The seedling grows leaves to make its own food, through photosynthesis in a grateful mood!\nThe plant grows bigger with stems and leaves so green, the most beautiful thing ever seen!\nFlowers bloom with colors so bright and fair, attracting insects to visit and share!\nThe flower becomes a fruit with seeds inside, the cycle continues with nature as guide!`,
    'Natural Disasters': `🎵 Natural disasters are powerful events of nature's might, causing damage to the world day or night!\nEarthquakes shake the ground when tectonic plates shift and move, causing buildings and roads to shake and remove!\n\n🎵 Chorus: Natural disasters strong and grand, happening across the land!\n\n🎵 Volcanoes erupt with lava flowing hot and red, ash and smoke rise high overhead!\nFloods happen when too much rain fills rivers and seas, rising water covers land with ease!\nHurricanes and cyclones are strong winds that spin around, causing destruction on the ground!\nTsunamis are huge waves caused by quakes under the sea, always be prepared and safety is the key!`,
    'Simple Machines': `🎵 A lever has a bar and a fulcrum as its base, helping lift heavy things with ease and grace!\nA pulley uses a wheel and rope to lift things high, like a flag on a pole reaching the sky!\n\n🎵 Chorus: Simple machines help us work, they never ever shirk!\n\n🎵 An inclined plane is a ramp sloping up or down, like a slide in the park or a ramp into the town!\nA wedge is sharp and splits things apart like an axe does to wood, a needle or a knife work just as good!\nA screw is a spiral that holds things together tight, like a jar lid or a bolt that makes things right!\nA wheel and axle help things roll along so free, like on a bicycle or a car for me!`,
    'Force & Energy': `🎵 Energy is the ability to do work you see, it comes in many forms for you and for me!\nKinetic energy is moving energy like a running child, potential energy is stored energy like a ball held still!\n\n🎵 Chorus: Energy energy all around, in light in heat in every sound!\n\n🎵 Light energy comes from the Sun and bulbs so bright, heat energy warms us day and night!\nSound energy travels in waves that reach our ear, electrical energy powers things far and near!\nChemical energy is stored in food and battery too, nuclear energy from atoms is powerful and new!\nEnergy cannot be created or destroyed they say, it only changes form day by day!`
  },
  spelling: {
    'Sight Words': `🎵 Sight words are words you know by sight at once, you read them fast without a grunt!\nThe word 'the' we use everywhere, in every book and everywhere!\n\n🎵 Chorus: Sight words help us read each day, in the books we read and play!\n\n🎵 'I' and 'you' and 'we' and 'they', are words we use every single day!\n'And' and 'are' and 'can' and 'do', these words we see in books brand new!\n'For' and 'go' and 'has' and 'he', these words help you and help me!\nPractice sight words every day, with flash cards in the classroom and at play!`,
    'Phonics': `🎵 A says ah like in apple so sweet, B says buh like in ball when we meet!\nC says kuh like in cat so small, each letter makes a special call!\n\n🎵 Chorus: Phonics helps us sound out words, the best way ever heard!\n\n🎵 D says duh like in dog that barks all day, E says eh like in elephant at play!\nF says fuh like in fish that swims, G says guh like in go that begins!\nH says huh like in hat on my head, I says ih like in igloo as we said!\nJ says juh like in jug so round, K says kuh like in kite that is found!`,
    'Alphabet': `🎵 The alphabet has twenty-six letters in a row, A B C D E F G watch them go!\nKnowing every letter big and small, helps us learn to read and write them all!\n\n🎵 Chorus: The alphabet from A to Z, learning letters is the key!\n\n🎵 Vowels are A E I O and U, the rest are consonants through and through!\nA is the first letter so you see, Z is the last letter for you and me!\nEach letter has a capital form so tall, and a lowercase version small!\nLetters make words that we read and write, learning the alphabet is our reading light!`,
    'Short Vowels': `🎵 Short vowel sounds are quick and short you see, A says ah in apple for me!\nE says eh in elephant so wide, I says ih in igloo inside!\n\n🎵 Chorus: Short vowels ah eh ih aw and uh, learning them is good enough!\n\n🎵 O says aw in octopus so neat, U says uh in umbrella complete!\nShort A in cat and bat and hat, short E in bed and red and that!\nShort I in pig and wig and pin, short O in dog and log and bin!\nShort U in cup and pup and sun, short vowel sounds are so much fun!`,
    'Long Vowels': `🎵 Long vowels say their own name you see, A says ay in cake for me!\nE says ee in bee that flies so high, I says eye in kite up in the sky!\n\n🎵 Chorus: Long vowels sounds long and clear, helping us read far and near!\n\n🎵 O says oh in home and bone, U says yoo in cube and cone!\nLong A in make and take and cake, long E in keep and sleep and lake!\nLong I in time and lime and kite, long O in hope and rope and light!\nLong U in cute and mute and tune, long vowels morning night and noon!`,
    'Blends & Digraphs': `🎵 Consonant blends are two consonants together you see, each sound is heard like bl in blue for me!\nBr in brown cr in crow dr in drum, they blend together as they come!\n\n🎵 Chorus: Blends and digraphs in words we find, helping us read with our mind!\n\n🎵 Digraphs are two letters that make one sound you know, sh makes shh like in ship that goes slow!\nCh makes chh like in cheese and chair, th makes thh like in think and there!\nWh makes wh like in whale and when, ph makes f like in phone and then!\nBlends like st in star and sp in spot, fl in flag and gl in dot!`,
    'Contractions': `🎵 Contractions are two words joined as one you see, with an apostrophe showing where letters used to be!\nDo not becomes don't with the o left out, can not becomes can't without a doubt!\n\n🎵 Chorus: Contractions shorten words with ease, making our language flow with breeze!\n\n🎵 I am becomes I'm with the a gone, you are becomes you're moving on!\nWe will becomes we'll with wi replaced, they have becomes they've to be faced!\nIs not becomes isn't are not becomes aren't, was not becomes wasn't a grammar servant!\nWill not becomes won't a special case indeed, contractions help us when we read!`,
    'Homophones': `🎵 Homophones sound the same but their meanings differ so, their spellings are different as everyone should know!\n'There' is a place 'their' shows belonging for you, 'they're' means they are as easy as can do!\n\n🎵 Chorus: Same sound different spelling same sound different meaning!\n\n🎵 'To' is for direction 'too' means also or too much, 'two' is the number as easy as such!\n'Here' means this place 'hear' means with our ears, hearing homophones loud and clear!\n'By' means near or who made it you see, 'buy' means to purchase 'bye' means goodbye to be!\n'Sun' shines in the sky 'son' is a boy like me, 'see' with our eyes and 'sea' is water in the sea!`,
    'Compound Words': `🎵 Compound words are two small words joined as one, like rain and bow make rainbow after day is done!\nSun and flower make sunflower facing the sun so bright, compound words help our reading take flight!\n\n🎵 Chorus: Rain plus bow equals rainbow across the sky, foot plus ball equals football we kick so high!\n\n🎵 Bed plus room equals bedroom where we sleep at night, door plus bell equals doorbell ringing with all might!\nButter plus fly equals butterfly fluttering in the air, star plus fish equals starfish beyond compare!\nSnow plus man equals snowman built when snow does fall, every compound word is a word that has it all!\nCup plus cake makes cupcake so sweet to eat, every compound word is a learning treat!`,
    'Spelling Lists': `🎵 Spell 'school' with S-C-H-O-O-L, spell 'friend' F-R-I-E-N-D and you are cool!\nSpell 'because' with B-E-C-A-U-S-E, knowing spelling sets your mind at ease!\n\n🎵 Chorus: Practice spelling every word each day, the best speller in every way!\n\n🎵 Spell 'beautiful' B-E-A-U-T-I-F-U-L so grand, spell 'people' P-E-O-P-L-E across the land!\nSpell 'library' L-I-B-R-A-R-Y in the books we see, spelling rules help you and me!\n'I before E except after C' is a rule to know, in words like 'believe' and 'receive' the letters go!\nDrop the E before adding ING in words like make to making, spelling rules are good for taking!`,
    'Prefixes & Suffixes': `🎵 A prefix is added to the beginning of a word you see, it changes the meaning for you and for me!\n'Un' means not like in unhappy or unsure, 're' means again like in redo or restore!\n\n🎵 Chorus: Prefixes at the start suffixes at the end, changing words with every friend!\n\n🎵 'Pre' means before like in preview or prepay, 'dis' means not like in dislike or display!\n'Mis' means wrong like in misplace or mistake, understanding prefixes is a cake you make!\nA suffix is added to the end of a word, '-ful' means full of like in beautiful as heard!\n'-less' means without like in fearless or endless, '-ly' turns adjectives to adverbs I guess!`,
    'Silent Letters': `🎵 Silent letters are letters that are not pronounced at all, in words like knee and write and fall!\nThe K is silent in knee and knife and know, the W is silent in write and wrist and woe!\n\n🎵 Chorus: Silent letters quiet and still, in many words against our will!\n\n🎵 The B is silent in comb and thumb and debt, the G is silent in gnome and sign and get!\nThe H is silent in hour and honest and ghost, the T is silent in castle and listen most!\nThe L is silent in half and calf and talk, the P is silent in psychology when we talk!\nThe U is silent in guard and guess and guide, silent letters like to hide!`,
    'Greek & Latin Roots': `🎵 Many English words come from Greek and Latin roots you see, knowing the root helps guess the meaning for me!\n'Bio' from Greek means life like in biology and biography, 'Graph' means write like in autograph and geography!\n\n🎵 Chorus: Greek and Latin roots unlock, word meanings like a key to a lock!\n\n🎵 'Tele' means far like in telephone and telescope, 'Phone' means sound like in microphone full of hope!\n'Astro' means star like in astronaut and astronomy, 'Geo' means earth like in geology for me!\n'Aqua' means water like in aquarium and aquatic, 'Dict' means say like in dictionary and predict!\n'Port' means carry like in transport and export, 'Struct' means build like in construct and report!`,
    'Vocabulary': `🎵 A synonym means the same like big and large you see, an antonym means opposite like hot and cold for me!\nExpanding our vocabulary every day, helps us in what we read and say!\n\n🎵 Chorus: Words words words we learn, every single page we turn!\n\n🎵 Happy and joyful are synonyms so fine, sad and unhappy are synonyms in line!\nFast and quick are synonyms as can be, slow and sluggish are synonyms for me!\nUp and down are antonyms as opposites, in and out are antonyms you get it!\nA dictionary helps us find word meanings so clear, thesaurus helps find synonyms far and near!`,
    'Dictionary Skills': `🎵 Words in a dictionary are in alphabetical order you see, from A to Z as easy as can be!\nGuide words at the top of each page show, the first and last word on the page you know!\n\n🎵 Chorus: Dictionary skills help us find, word meanings of every kind!\n\n🎵 Each entry has the spelling pronunciation and part of speech, the definition and a sentence within your reach!\nThe pronunciation guide in brackets shows how to say, the word with syllables in a helpful way!\nSome entries show the word's origin where it came from, like from Latin or Greek or kingdom!\nUsing a dictionary every day, helps us learn in every way!`,
    'Word Building': `🎵 Word building is making new words from old ones you see, adding prefixes and suffixes helps you and me!\nFrom the root word 'play' we get player and playful and replay, building words in a wonderful way!\n\n🎵 Chorus: Build new words from roots so grand, with our minds and hand!\n\n🎵 Adding -er to teach makes a teacher who shows, adding -ing to run makes running as it goes!\nAdding re- to do makes redo to do again, adding un- to happy makes unhappy in the rain!\nAdding -ful to help makes helpful as can be, adding -less to help makes helpless as we see!\nWord families like cat bat hat and mat, help us learn words like that!`
  },
  geography: {
    'Continents': `🎵 Seven continents on planet Earth we know, Asia Africa Europe let us go!\nNorth America South America too, Antarctica and Australia for you!\n\n🎵 Chorus: Seven continents seven lands, each one beautiful and grand!\n\n🎵 Asia is the biggest continent so wide, with Russia China and India inside!\nAfrica has deserts and jungles so grand, the Nile River flows across the land!\nNorth America from Canada to Mexico wide, South America with the Amazon inside!\nEurope has many countries old and new, Antarctica is cold with ice and snow for you!\nAustralia is a country and a continent too, surrounded by ocean water blue!`,
    'Countries': `🎵 Countries are different lands with flags and names of their own, each country unique and known!\nIndia has the Taj Mahal so white and grand, China has the Great Wall across the land!\n\n🎵 Chorus: Every country has its own flag and name, learning about them is a wonderful game!\n\n🎵 The United States has fifty states across the land, France has the Eiffel Tower so grand!\nJapan has cherry blossoms in the spring, Brazil has the Amazon and carnival swing!\nAustralia has kangaroos and koala bears, Canada has maple leaves and cold air!\nEach country has a capital city where the government stays, learning countries in many ways!`,
    'Landforms': `🎵 Mountains reach high up to the sky so tall, valleys lie low where rivers flow through all!\nPlains are flat and wide across the land, plateaus are flat on top rising high and grand!\n\n🎵 Chorus: Landforms shape the Earth we know, from mountain tops to plains below!\n\n🎵 A hill is smaller than a mountain tall, a desert is dry with very little rainfall!\nAn island is land surrounded by water all around, a peninsula is land with water on three sides found!\nA river flows from mountains to the sea so wide, a lake is a body of water with land on every side!\nAn ocean is the largest body of water there be, the Pacific is the largest as far as we can see!`,
    'Maps': `🎵 A map is a drawing of a place you see, showing where things and places be!\nA compass rose shows directions North South East West, helping us find our way and do our best!\n\n🎵 Chorus: Maps help us find our way around, in the city and in the town!\n\n🎵 The legend shows what symbols on the map mean, like a tree for a park or a building scene!\nThe scale shows how distance on the map relates to real land, like one inch equals one mile as we understand!\nA globe is a model of the Earth round and blue, showing continents and oceans for you!\nLatitude lines go east-west around the sphere, longitude lines go north-south to make the grid clear!`,
    'Climate': `🎵 Climate is the weather pattern over many years you see, different from weather that changes daily for me!\nThe Earth has climate zones tropical temperate and polar too, each one different in what they do!\n\n🎵 Chorus: Climate patterns over time, in every country and every clime!\n\n🎵 Tropical climate near the equator is hot all year, rainforests grow lush and green and clear!\nTemperate climate has four seasons spring summer fall and winter too, mild weather for me and you!\nPolar climate near the poles is cold with ice and snow, where penguins and polar bears go!\nDesert climate is very dry with little rain to fall, hot in the day and cold at night overall!\nFactors like latitude altitude and oceans affect climate zone, each climate region is differently known!`,
    'Natural Resources': `🎵 Natural resources are gifts from the Earth so kind, everything we use from nature we find!\nWater air soil minerals and trees, resources like these help us with ease!\n\n🎵 Chorus: Natural resources nature's treasure, use them wisely with pleasure!\n\n🎵 Renewable resources can be used again and again, like sunlight wind and falling rain!\nTrees can be replanted so they regrow, water cycles so it continues to flow!\nNon-renewable resources like coal and oil take millions of years to make, once used up they are gone for goodness sake!\nWe must conserve resources and use them with care, saving energy and water everywhere!\nReduce reuse recycle is the key, to protect our resources for you and for me!`
  }
};

function getLyricsForTopic(subject, topic) {
  const subjMap = { math: 'math', science: 'science', spelling: 'spelling', geography: 'geography' };
  const subj = subjMap[subject] || 'math';
  const tn = topic.trim().toLowerCase();
  const tnNorm = normalize(tn);
  const keys = Object.keys(lyricsMap[subj] || {});

  let matched = keys.find(k => k.toLowerCase() === tn);
  if (!matched) {
    const sk = synonymKeys[topic.trim()] || synonymKeys[tn];
    if (sk) {
      const [skSubj, skKey] = sk.split(':');
      if (skSubj === subj) matched = keys.find(k => k.toLowerCase() === skKey.toLowerCase());
    }
  }
  if (!matched) matched = keys.find(k => normalize(k) === tnNorm);
  if (!matched) {
    const tnTokens = tn.split(/\s+/).filter(t => t.length > 2);
    let bestScore = 0;
    for (const k of keys) {
      const kTokens = k.toLowerCase().split(/\s+/).filter(t => t.length > 2);
      const score = tnTokens.filter(t => kTokens.includes(t)).length;
      if (score > bestScore) { bestScore = score; matched = k; }
    }
    if (bestScore < 1) matched = null;
  }
  if (!matched) matched = keys[0] || 'Shapes';

  return lyricsMap[subj][matched];
}

export { getLyricsForTopic, lyricsMap };
